server:
  port: 8081

spring:

  application:
    name: ToolsForDS
  datasource:
    url: jdbc:postgresql://192.168.88.105:5432/dstools_db
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 16
      auto-commit: false
      connection-timeout: 10000
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: PostgreSQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:liquibase/changelog/changelog.xml
  data:
    neo4j:
      open-in-view: false

logging:
  file:
    name: log/app.log